services:
  api:
    container_name: assassinsmanager-api
    image: goam/goam-api
    build:
      context: .
      dockerfile: Api.Dockerfile
    depends_on:
      - db
    ports:
      - 80:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:MySql=server=assassinsmanager-db;user=root;password=RandomPassword;database=assassinsmanager

  discord:
    container_name: assassinsmanager-discord
    image: goam/goam-discord
    build:
      context: .
      dockerfile: DiscordBot.Dockerfile
    depends_on:
      - api

  db:
    container_name: assassinsmanager-db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=RandomPassword
    volumes:
      - ./mysql:/var/lib/mysql