services:
  website:
    container_name: assassins-website
    image: oga/oga-site:latest
    build:
      context: .
      dockerfile: Website.Dockerfile
    volumes:
      - ./assassins-website/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    networks:
      - nginx-router
    # depends_on:
      # - api

  api:
    container_name: assassinsmanager-api
    image: oga/ogam-api
    build:
      context: .
      dockerfile: Api.Dockerfile
    depends_on:
      - db
    env_file:
      - ./api.env
    networks:
      - nginx-router

  discord:
    container_name: assassinsmanager-discord
    image: oga/ogam-discord
    build:
      context: .
      dockerfile: DiscordBot.Dockerfile
    depends_on:
      - api
    env_file:
      - ./discord.env
    networks:
      - nginx-router

  db:
    container_name: assassinsmanager-db
    image: mariadb
    env_file:
      - ./api.env
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./db-config:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - nginx-router
  
networks:
  nginx-router:
    name: nginx-router
    external: true