services:      
  website:
    container_name: assassins-website
    image: oga/oga-site
    ports:
      - 80:80
      - 443:443
    build:
      context: .
      dockerfile: Website.Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

  api:
    container_name: assassinsmanager-api
    image: oga/ogam-api
    build:
      context: .
      dockerfile: Api.Dockerfile
    depends_on:
      - db
    env_file:
      - ./api.env

  discord:
    container_name: assassinsmanager-discord
    image: oga/ogam-discord
    build:
      context: .
      dockerfile: DiscordBot.Dockerfile
    depends_on:
      - api
    env_file:
      - ./discord.env

  db:
    container_name: assassinsmanager-db
    image: mariadb
    env_file:
      - ./api.env
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./db-config:/docker-entrypoint-initdb.d/:ro
    # ports:
    #   - 3306:3306
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3