services:
  nginx:
    container_name: assassins-nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      
  website:
    container_name: assassins-website
    image: oga/oga-site
    build:
      context: ./assassins-website

  api:
    container_name: assassinsmanager-api
    image: oga/ogam-api
    build:
      context: .
      dockerfile: Api.Dockerfile
    depends_on:
      - db
    env_file:
      - ./api.env

  discord:
    container_name: assassinsmanager-discord
    image: oga/ogam-discord
    build:
      context: .
      dockerfile: DiscordBot.Dockerfile
    depends_on:
      - api
    env_file:
      - ./discord.env

  db:
    container_name: assassinsmanager-db
    image: mysql
    env_file:
      - ./api.env
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db-config:/docker-entrypoint-initdb.d/:ro
    # ports:
    #   - 3306:3306